// Verifies every live section time (sections.js) and every wave/obstacle time
// (waves.js) sits on a real track beat. Usage: yarn check:beats [--fix]
// --fix rewrites off-grid section times only; waves.js is generated by
// tools/gen-waves.py, so wave failures must be fixed by regenerating it.
import { readFileSync, writeFileSync } from 'node:fs';
import { SECTIONS } from '../src/config/sections.js';
import { WAVES } from '../src/config/waves.js';
import { snapToTrackBeat, trackBeatOf } from '../src/Conductor.js';

const TOLERANCE_MS = 1;
// songTime and timeOffset are each rounded to integer ms, so errors can stack to ~1 ms.
const WAVE_TOLERANCE_MS = 1.5;
const FIELDS = ['startMs', 'endMs'];
const SOURCE = new URL('../src/config/sections.js', import.meta.url);
const fix = process.argv.includes('--fix');

function beatTag(ms) {
  const beat = trackBeatOf(ms);
  let tag = `beat ${beat}`;
  if (beat % 4 === 0) tag += ', bar start';
  if (beat % 8 === 4) tag += ', phrase start';
  return { beat, tag };
}

const changes = [];
for (const section of SECTIONS) {
  for (const field of FIELDS) {
    const ms = section[field];
    const target = snapToTrackBeat(ms);
    const label = `${section.name}.${field}`;
    if (Math.abs(target - ms) > TOLERANCE_MS) {
      const snapped = Math.round(target);
      const { tag } = beatTag(snapped);
      console.log(`✗ ${label} ${ms} → ${snapped} (${tag}, moved ${snapped - ms} ms)`);
      changes.push({ name: section.name, field, from: ms, to: snapped });
    } else {
      console.log(`✓ ${label} ${ms} (${beatTag(ms).tag})`);
    }
  }
}

if (!changes.length) {
  console.log('All section times are on a real track beat.');
} else if (!fix) {
  console.log(`\n${changes.length} off-grid section time(s). Run \`yarn check:beats --fix\` to rewrite them.`);
}

let waveTimes = 0;
let waveFailures = 0;
function checkWaveTime(label, ms) {
  waveTimes++;
  const target = snapToTrackBeat(ms);
  if (Math.abs(target - ms) <= WAVE_TOLERANCE_MS) return;
  waveFailures++;
  console.log(`✗ ${label} ${ms} (nearest beat ${trackBeatOf(ms)}, off ${(ms - target).toFixed(1)} ms)`);
}
console.log('');
for (const wave of WAVES) {
  checkWaveTime(`waves.${wave.name}.songTime`, wave.songTime);
  wave.obstacles.forEach((o, i) => checkWaveTime(`waves.${wave.name}.obstacles[${i}]`, wave.songTime + o.timeOffset));
}
if (!waveFailures) {
  console.log(`✓ waves: ${waveTimes} times on a real track beat`);
} else {
  console.log(`\n${waveFailures} off-grid wave time(s). waves.js is generated — never hand-edit; regenerate with:`);
  console.log('  uv run --with librosa --with numpy python tools/gen-waves.py');
}

if (!changes.length || !fix) process.exit(waveFailures || changes.length ? 1 : 0);

const lines = readFileSync(SOURCE, 'utf8').split('\n');
const live = lines.map((line, i) => ({ line, i })).filter(({ line }) => !line.trim().startsWith('//'));
for (const name of new Set(changes.map(c => c.name))) {
  const matches = live.filter(({ line }) => line.includes(`name: '${name}'`));
  if (matches.length !== 1) {
    console.error(`Cannot find a unique live line for section '${name}' (${matches.length} found); nothing written.`);
    process.exit(1);
  }
  const target = matches[0];
  for (const c of changes.filter(c => c.name === name)) {
    const re = new RegExp(`(${c.field}:\\s*)\\d+(\\.\\d+)?`);
    if (!re.test(target.line)) {
      console.error(`Cannot find ${c.field} on the line for '${name}'; nothing written.`);
      process.exit(1);
    }
    target.line = target.line.replace(re, `$1${c.to}`);
  }
  lines[target.i] = target.line;
}
writeFileSync(SOURCE, lines.join('\n'));
console.log(`\nRewrote ${changes.length} value(s):`);
for (const c of changes) console.log(`  ${c.name}.${c.field} ${c.from} → ${c.to}`);
process.exit(waveFailures ? 1 : 0);
